version: "3.8"

services:
  app:
    build: 
      context: ./
      dockerfile: nodejsdockerfile
    ports:
      - "3000:3000"  
    depends_on:
      - db

  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx:
    build: 
      context: ./
      dockerfile: nginxdockerfile
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    
volumes:
  pgdata: