version: "3.8"

services:
  app:
    build: 
      context: .
      dockerfile: ./nodejs/Dockerfile
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
    ports:
      - "3000:3000"  
    depends_on:
      - db

  db:
    build:
      context: ./postgresql
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  nginx:
    build: 
      context: ./nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    
volumes:
  pgdata: